### ISSUE TITLE
Password for vnc?

### ISSUE THREAD

**Issue by wjgeorge** [queeno/docker-ubuntu-desktop#3]
i see you set a password, but I cant find a mention of it.

my quick fix:

docker run -it -p 5901:5901 queeno/ubuntu-desktop bash
vncpasswd
vncserver

**Comment by queeno** [comment]
Hi @wjgeorge 

Thanks for opening this issue. VNC's password is `password`.

I've updated the README.md file to explicitly state that.

Let me know if you have more issues.

Simon
